/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Clases.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author francootero
 */
public class Ejercicio3 extends javax.swing.JFrame {
    
    private static Vector<Imagen> imagenes;
    Vector< Integer> simbolosOriginal;
    private int [] cantOriginal ;
    private Vector<SimboloProbabilidad> probabilidadesOriginal;
    private Vector<NodoArbol> arbolOriginal;
    private Vector<Codificacion> codifOriginal;
    private ByteEncoding helper;
    private Vector<Integer> simbolosPolicia;
    private int [] cantPolicia;
    private Vector<SimboloProbabilidad> probabilidadesImgPolicia;
    private Vector<NodoArbol> arbolImgPolicia;
    private Vector<Codificacion> codifImgPolicia;

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3(javax.swing.JFrame parent, boolean modal, Vector<Imagen> imagenes) {
       
   
        initComponents();
        helper = new ByteEncoding();
        this.imagenes = imagenes;
        simbolosOriginal = imagenes.get(0).getSimbolos();
        cantOriginal = new int [imagenes.get(0).getColores()];
        probabilidadesOriginal = imagenes.get(0).getProbabilidades(simbolosOriginal, cantOriginal);
        arbolOriginal = helper.arbolDeHuffman(probabilidadesOriginal);
        codifOriginal = helper.getSimbolosCodificados(arbolOriginal);
        
        simbolosPolicia = new Vector<Integer>();
        int[] cantidadPolicia = new int [imagenes.get(0).getColores()];
        ByteEncoding helper = new ByteEncoding();
        probabilidadesImgPolicia = imagenes.get(2).getProbabilidades(simbolosPolicia, cantidadPolicia);
        arbolImgPolicia = helper.arbolDeHuffman(probabilidadesImgPolicia);
        codifImgPolicia = helper.getSimbolosCodificados(arbolImgPolicia);
        
                
        
    }

    private Ejercicio3() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Comprimir con Huffman semi-estático la imagen original.");

        jLabel2.setText("Comprimir la imagen del resultado más parecido con el código de Huffman asociado a la imagen original.");

        jLabel3.setText("Comprimir la imagen que trajo el policía con el código de Huffman asociado a la imagen original.");

        jLabel4.setText("Comprimir la imagen que trajo el policía utilizando Huffman semi-estático, esta vez utilizando el código generado para la propia imagen.");

        jLabel5.setText("Comparar las tasas de compresión obtenidas. ");

        jLabel6.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        jLabel6.setText("Compresión de Imagenes:");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ejecutar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ejecutar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Ejecutar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Calcular Tasas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       JOptionPane.showMessageDialog(null, "Cargando...puede demorar varios minutos. Los archivos apareceran en la carpeta 'generados'.");
        
        helper.encodeSequence(imagenes.get(0).getSecuencia(), codifOriginal, simbolosOriginal, cantOriginal, "generados/comprimidoOriginal.txt");
        helper.decodeSequence("generados/comprimidoOriginal.txt", "generados/descompresionOriginal.bmp");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        JOptionPane.showMessageDialog(null, "Cargando...puede demorar varios minutos. Los archivos apareceran en la carpeta 'generados'.");
  
        helper.encodeSequence(imagenes.get(1).getSecuencia(), codifOriginal, simbolosOriginal, cantOriginal,"generados/comprimidoMasParecido.txt");
        helper.decodeSequence("generados/comprimidoMasParecido.txt", "generados/descompresionMasParecido.bmp");
        
            }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         JOptionPane.showMessageDialog(null, "Cargando...puede demorar varios minutos. Los archivos apareceran en la carpeta 'generados'.");

        helper.encodeSequence(imagenes.get(2).getSecuencia(), codifOriginal, simbolosOriginal,cantOriginal,"generados/comprimidoImgPolicia1.txt");
        helper.decodeSequence("generados/comprimidoImgPolicia1.txt", "generados/descompresionImgPolicia1.bmp");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        JOptionPane.showMessageDialog(null, "Cargando...puede demorar varios minutos. Los archivos apareceran en la carpeta 'generados'.");

        helper.encodeSequence(imagenes.get(2).getSecuencia(), codifImgPolicia, simbolosPolicia, cantPolicia,"generados/comprimidoImgPolicia2.txt");
        helper.decodeSequence("generados/comprimidoImgPolicia2.txt", "generados/descompresionImgPolicia2.bmp");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    Vector<Double> lista = new Vector<Double>();
    
    String archivo1 = "../TpTeoInfo/src/Imagenes/Will(Original).bmp";
    long longitud1 = new File(archivo1).length();
    lista.add(Double.valueOf(longitud1));
    
    String archivo2 = "../TpTeoInfo/generados/descompresionOriginal.bmp";
    long longitud2 = new File(archivo2).length();
    lista.add(Double.valueOf(longitud2));
    
    String archivo3 = "../TpTeoInfo/src/Imagenes/Will_1.bmp";
    long longitud3 = new File(archivo3).length();
    lista.add(Double.valueOf(longitud3));
    
    String archivo4 = "../TpTeoInfo/generados/descompresionMasParecido.bmp";
    long longitud4 = new File(archivo4).length();
    lista.add(Double.valueOf(longitud4));
    
    String archivo5 = "../TpTeoInfo/src/Imagenes/Will_ej2.bmp";
    long longitud5 = new File(archivo5).length();
    lista.add(Double.valueOf(longitud5));
    
    String archivo6 = "../TpTeoInfo/generados/descompresionImgPolicia1.bmp";
    long longitud6 = new File(archivo6).length();
    lista.add(Double.valueOf(longitud6));
    
    String archivo7 = "../TpTeoInfo/generados/descompresionImgPolicia2.bmp";
    long longitud7 = new File(archivo7).length();
    lista.add(Double.valueOf(longitud7));
    
    Vector<Double> resultado = new Vector<Double>();
    resultado.add(lista.elementAt(0)/lista.elementAt(1));
    resultado.add(lista.elementAt(2)/lista.elementAt(3));
    resultado.add(lista.elementAt(4)/lista.elementAt(5));
    resultado.add(lista.elementAt(4)/lista.elementAt(6));

    
    Tasas t = new Tasas(this, true, resultado);
    t.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
